### ISSUE TITLE
Missing parameter for API Key

### ISSUE THREAD

**Issue by theghostofc** [projectkudu/SimpleWAWS#18] opened 2016-04-05 11:24 UTC
[ToDoActivity.txt](https://github.com/projectkudu/SimpleWAWS/files/204317/ToDoActivity.txt)

The code is missing the API Key parameter where mClient object is initialized in the onCreate method.

Where can I get the API Key for the app generated using Try Azure App Service?

**Comment by lindydonna** [comment] 2016-04-05 20:20
Try App Service uses the Mobile Apps, rather than the older Mobile Services. Mobile Apps no longer uses an API key. See https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-net-upgrading-from-mobile-services/#updating-clients.

**Comment by davidebbo** [comment] 2016-04-05 22:34
Re-opening, as @lindydonna found that we in fact has an old version, and that it does have that issue.

**Comment by lindydonna** [comment] 2016-04-05 22:34
We have an old version of the Android project on Try App Service, thanks for filing the bug. We're fixing the issue now.

**Comment by lindydonna** [comment] 2016-04-11 23:11
Duplicate of #21.

**Closed by lindydonna** 2016-04-11 23:11 UTC
