### ISSUE TITLE
AppKey TryMobileApp

### ISSUE THREAD

**Issue by rgavelino** [projectkudu/SimpleWAWS#31] opened 2016-06-23 21:31 UTC
Client Android there isn't appkey...

  // Mobile Service URL and key
            mClient = new MobileServiceClient(
                    "https://efb426d6-0ee0-4-231-b9ee.azurewebsites.net/",
                    this).withFilter(new ProgressFilter());

 public MobileServiceClient(String appUrl, String appKey, Context context) throws MalformedURLException {
        this(new URL(appUrl), appKey, context);
    }

**Comment by rgavelino** [comment] 2016-06-23 21:49
just solved... put "null" at second parameter...

**Comment by lindydonna** [comment] 2016-07-07 01:06
This is a duplicate of #21.

**Closed by lindydonna** 2016-07-07 01:06 UTC
