### ISSUE TITLE
TryMobileApp for Android does not work

### ISSUE THREAD

**Issue by qoopooh** [projectkudu/SimpleWAWS#15] opened 2016-02-04 03:51 UTC
I got sample Android project from https://tryappservice.azure.com/
After execute the app on device, you will get the error message:
{"message":"No API version was specified .... ZUMO-API-VERSION of '2.0.0' "}

**Comment by lindydonna** [comment] 2016-04-11 23:12
Duplicate of #21.

**Closed by lindydonna** 2016-04-11 23:12 UTC
