### ISSUE TITLE
Project crashes

### ISSUE THREAD

**Issue by ricardo-1937** [projectkudu/SimpleWAWS#16] opened 2016-03-03 00:49 UTC
Downloaded project does not run properly, there are also no instructions on what has to be done to avoid it, there is not even a database diagram or script provided.

**Comment by lindydonna** [comment] 2016-04-05 20:24
Could you be more specific about which project does not work?

**Comment by ricardo-1937** [comment] 2016-04-05 22:18
Project crashes when it cannot access the database.




Ricardo Sanchez
(561) 372-9299

 
Date: Tue, 5 Apr 2016 13:31:34 -0700

**Comment by lindydonna** [comment] 2016-04-05 22:33
Which project?  There are multiple projects in Try App Service.

**Comment by ricardo-1937** [comment] 2016-04-05 22:45
The message did not specify the project.
It is simple to reproduce, you just download it into a new Windows 10 installation, unzip and try to run it.
It will then crash.
I have already removed the software from my PC and do not wish to repeat the experience.
I have IIS installed with Directory Browsing and VS 2015 with all the updates.




Ricardo Sanchez
(561) 372-9299

 
Date: Tue, 5 Apr 2016 15:33:44 -0700

**Comment by lindydonna** [comment] 2016-04-05 22:54
Did you download a project from GitHub, or from Try App Service?  We are not able to reproduce the issue.

**Comment by ricardo-1937** [comment] 2016-04-05 23:38
I downloaded from GitHub.
 I have a brand new Dell with Windows 10 professional.




Ricardo Sanchez
(561) 372-9299

 
Date: Tue, 5 Apr 2016 15:54:18 -0700

**Comment by lindydonna** [comment] 2016-04-05 23:48
What are you trying to accomplish?  This repo is for making contributions to Try App Service. If you want to use Try App Service instead, go to https://tryappservice.azure.com. If you're having problems with one of those downloading projects, please tell us which one is failing.

**Comment by ricardo-1937** [comment] 2016-04-06 00:13
I am in the process of downloading the project again and installing it.
Your attention and support is unprecedented in my experience and I want to help.
After I run it again, I will send you a screen shot of the crash.




Ricardo Sanchez
(561) 372-9299

 
Date: Tue, 5 Apr 2016 16:48:38 -0700

**Comment by ricardo-1937** [comment] 2016-04-06 01:25
I do not have azure.
In this download from GitHub, it does not build, I get over 700 errors.




Ricardo Sanchez
(561) 372-9299

 
Date: Tue, 5 Apr 2016 16:48:38 -0700

**Comment by lindydonna** [comment] 2016-04-06 01:27
What are you trying to accomplish?  If you don't have Azure, you won't be able to do much with this repo. This is for adding functionality to Try App Service on Azure.

**Comment by ricardo-1937** [comment] 2016-04-06 01:32
I missed that objective, I thought it was an MVC example.




Ricardo Sanchez
(561) 372-9299

 
Date: Tue, 5 Apr 2016 18:27:34 -0700

**Comment by lindydonna** [comment] 2016-04-06 01:35
Yes, it's the engine behind Try App Service, as noted in the description. You are probably missing the Azure SDK and that's why you're getting build errors. We'll close this issue.

**Closed** 2016-04-06 16:01 UTC
